// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cloud_logic_custom": [
        {
            "name": "sagemaker",
            "endpoint": "https://5817p6g172.execute-api.us-west-2.amazonaws.com/prod",
            "region": "us-west-2"
        }
    ],
    "aws_content_delivery_bucket": "syd-summit-2019-aiml-20190425175147-hostingbucket-prod",
    "aws_content_delivery_bucket_region": "us-west-2",
    "aws_content_delivery_url": "http://syd-summit-2019-aiml-20190425175147-hostingbucket-prod.s3-website-us-west-2.amazonaws.com"
};


export default awsmobile;
